#! /bin/sh

# set up the two monitors for bspwm
# NOTE This is a simplistic approach because I already know the settings I
# want to apply.
xrandr --output HDMI1 --primary --output LVDS1 --right-of HDMI1
 bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9
 bspc monitor LVDS1 -d 0
#exec --no-startup-id xfce4-panel --disable-wm-check
#Polybar 
sh $HOME/.config/polybar/launch.sh
#Change keyboard layout
setxkbmap -option grp:alt_shift_toggle us,ara &

bspc config external_rules_command $HOME/.config/bspwm/android-emulator.sh
#Adding some tarnsparency 
picom &
#Wallpaper
nitrogen --restore &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a Chromium desktop='^2'
bspc rule -a Google-chrome desktop='^2'
bspc rule -a Emacs desktop='^1'
bspc rule -a qBittorrent desktop='^5'
bspc rule -a Emacs desktop='^1'
bspc rule -a Code desktop='^1'
bspc rule -a Mailspring desktop='^3'
bspc rule -a Spotify desktop='^4'
bspc rule -a cantata desktop='^4'
bspc rule -a zoom desktop='^5'
bspc rule -a TelegramDesktop desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Swap ESC key with Caps Lock key
xmodmap ~/.Xmodmap

